; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27031.1 

include listing.inc

INCLUDELIB MSVCRT

PUBLIC	?get_frames@Engine@NGINE@@QEBAHXZ		; NGINE::Engine::get_frames
; Function compile flags: /Ogtpy
;	COMDAT ?get_frames@Engine@NGINE@@QEBAHXZ
_TEXT	SEGMENT
this$ = 8
?get_frames@Engine@NGINE@@QEBAHXZ PROC			; NGINE::Engine::get_frames, COMDAT
; File d:\rex-animus\cxp-rewrite\libs\engine-build\src\engine-build.cpp
; Line 6
	mov	eax, 42					; 0000002aH
; Line 7
	ret	0
?get_frames@Engine@NGINE@@QEBAHXZ ENDP			; NGINE::Engine::get_frames
_TEXT	ENDS
END
